name: Build, test, release
on:
  push:
    paths:
      - release.yml
      - 'lib/**'
      - 'lib/version'
      - 'scripts/create-release.sh'
      - 'scripts/bump-version.sh'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.branch }}
  cancel-in-progress: true

jobs:
  should_release:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.outputs.skip }}
    steps:
      - uses: actions/checkout@v4
      - id: check
        run: |
          if [ "${GITHUB_REF}" != "refs/heads/main" ]; then
              echo "skip=true" >> "$GITHUB_OUTPUT"
              echo "⏭️ Skipping release because not on main branch." >> "$GITHUB_STEP_SUMMARY"
              exit 0
          fi

          body="$(git log -1 --pretty=%B | tail -n +2)"
          if echo "$body" | grep -qi 'skip release'; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "⏭️ Skipping release due to 'skip release' in commit message." >> "$GITHUB_STEP_SUMMARY"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
            echo "✅ Proceeding with release." >> "$GITHUB_STEP_SUMMARY"
          fi

  build_and_release:
    permissions:
      packages: write
      contents: write
    runs-on: ubuntu-latest
    needs: should_release
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - uses: gradle/actions/setup-gradle@v4

      - name: Test and build lib
        run: ./gradlew build

      - name: Publish package
        if: github.ref == 'refs/heads/main' && needs.should_release.outputs.skip == 'false'
        run: |
          ./gradlew publish
          ./scripts/create-release.sh
          ./scripts/bump-version.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summarize tests results
        uses: navikt/gradle-tests-summary@v1
        if: ${{ always() }}
